### ISSUE TITLE
Distinguer la démo / formation de la prod

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1058]
## Problème

Les agents (référents principalement) se retrouve parfois avec deux onglets RDV-Solidarités, un sur démo et l'autre sur la production. Difficile de faire la distinction entre les deux.

Seules les URLS peuvent nous renseigner (et sans doute les données que nous visualisons :)).

## Solution

1. Utiliser une couleur de fonds distinct pour la démo. _pas forcement très pratique vue qu'il y a déjà des codes couleurs pour distinguer usager et agent ?_
2. Une icône différente pour pouvoir distinguer les onglets dans le navigateur ? Là nous pourrions mettre une couleur différente sur le favicon. L'avantage de cette solution, c'est qu'elle permet aussi de distinguer dans les marques-pages
3. un bandeau texte en haut de la page, en permanence ?

J'opterais pour l'option 2 qui permet le meilleur rapport coût / impact.

## TODO 

- [ ] icone differente sur le web
- [ ] favicon differente (?)
- [ ] ajouter [DEMO] devant le sujet des mails, ou dans le contenu
- [ ] ajouter [DEMO] en premier mot des sms

**Comment by yaf** [comment]
À noter que ça serait intéressant d'avoir une icone différente pour la documentation et le forum également.

**Comment by adipasquale** [comment]
👍 gros +1 sur ce ticket, pas cher a faire et qui va eviter des erreurs a tout le monde nous y compris. 2 est indispensable mais pas suffisant a mon avis, je pense que 3 est une bonne piste pas chere et efficace mais pas tres belle, une autre piste est d'avoir un logo différent avec ecrit demo en gros par dessus (le logo est visible sur quasi toutes les pages je crois)
