### ISSUE TITLE
Permettre aux usagers de répondre directement aux agents

### ISSUE THREAD

**Issue by n-b** [betagouv/rdv-solidarites.fr#1649]
## Actuellement

Aujourd’hui, les mails de notifications aux usagers sont envoyés depuis l’adresse de contact de RDVS. Quand un usager répond, il répond donc à l’équipe de RDVS, et nous faisons manuellement suivre aux agents concernés. Il faudrait que ces messages soient directement envoyées aux agents concernés.

Par contre, on ne veut pas que les usagers voient l’adresse individuelle des agents.

## Attendu

Deux options avaient émergées de [nos premiers échanges](https://forum.rdv-solidarites.fr/t/mails-recus-par-lequipe-technique-incluant-des-informations-personnelles/120) à ce sujet 

1. Faire en sorte que l'adresse de réponse soit celle des services et organisations. Une sorte boite mail « générique » de service/organisation.
2. Mettre en place une redirection automatique, mais masqué : lorsqu'un usager répondrait à un email provenant de RDV-Solidarités, dans le cadre d'un rendez-vous, alors nous pourrions l'envoyer automatiquement, et de manière anonyme, à l'agent concerné.

La deuxième option nous semble la plus simple à mettre en place.

## Technique 

1. obtenir l’adresse email de contact des services et organisations et mettre cette adresse en `Reply-To`.
2. faire un système de relais dans RDVS. Github fait ça par exemple, en envoyant les mails depuis `notifications@github.com` et met dans le header `Message-ID` et `In-Reply-To` l’url de l’issue, pour permettre la réponse par mail. On pourrait faire pareil.

J’ai plutôt tendance à préférer le 2, ça me semble plus fiable à long terme. Par contre, on ne veut (sans doute) pas garder les réponses dans RDVS et en faire une app de chat. Mais on pourrait au moins garder les metadata des emails: ça nous permettrait de savoir que “le mail de notification a été envoyé” et “une réponse a été reçue”.

## Références

- https://forum.rdv-solidarites.fr/t/mails-recus-par-lequipe-technique-incluant-des-informations-personnelles/120

**Comment by yaf** [comment]
Utiliser Rails Mailbox ? https://edgeguides.rubyonrails.org/action_mailbox_basics.html

**Comment by yaf** [comment]
On tente mailbox

- [x] ajout d'un sous domaine app-mail.rdv-solidarites.fr
- [ ] ajout du sous domaine dans scalingo
- [ ] setup d'actionmailbox
- [ ] tester que mailbox reçoit bien les mails
- [ ] ...

**Comment by yaf** [comment]
Ou alors, on utilise les webhook de SendInBlue 

https://developers.sendinblue.com/docs/inbound-parse-webhooks

**Comment by francois-ferrandis** [comment]
Suite à des [discussions avec les autres startups](https://mattermost.incubateur.net/betagouv/pl/1ib8jcfui3fy7n97m9j7zuydkc) sur Mattermost, il semblerait que seuls les services américains proposent du "inbound email".

Je vais donc investiguer l'utilisation d'une boite Gandi et d'un petit job qui fait du polling [en POP3](https://ruby-doc.org/stdlib-3.0.3/libdoc/net/pop/rdoc/Net/POP3.html), ça semble le plus simple au final.

**Comment by francois-ferrandis** [comment]
@yaf Revirement de situation : je suis parvenu à faire fonctionner les webhook inbound de Sendinblue, on reçoit une requête vers [cette URL de test](https://webhook.site/#!/229cb0c5-d727-4aab-8d55-d4021bd1e3ae) lorsqu'un mail est envoyé à *@reply.rdv-solidarites.fr ! :tada: C'est OK niveau RGPD / données de santé ? :grimacing: 

Si oui je vais partir là-dessus, et si on a des difficultés on pourra passer par du POP3.

**Comment by yaf** [comment]
Super !

Niveau donnée de santé, de toute façon, c'est pas possible par mail (les 
utilisateurs n'ont pas de mail chiffré/sécurisé). Donc il faut éviter de 
faire transiter des données de santé dans les notifications...

Niveau RGPD c'est bon !

Il y a peut-être un truc à vérifier sur l'archivage des messages entrant 
chez eux ? Ça serait cool qu'il ne garde pas de trace ou pas trop longtemps.

Super en tout cas !
Reste que ça ne fonctionne pas pour les pièces jointes pour le moment je 
crois ?
