### ISSUE TITLE
Amélioration des performances

### ISSUE THREAD

**Issue by n-b** [betagouv/rdv-solidarites.fr#1754]
* [x] Suivi des recommandations de Bullet (#1745)
* [x] Upgrade de la base PG

Principaux points noirs selon skylight
* [x] [agent_searches_controller.rb#index](https://www.skylight.io/app/applications/RgR7i58P67xN/1632744420/2h40m/endpoints/Admin::Creneaux::AgentSearchesController%23index?responseType=html). SearchCreneauxForAgentsService est lent, en ruby et en sql.
* [x] Recherche full-text  [agent/searchable_concern user/searchable_concern](https://www.skylight.io/app/applications/RgR7i58P67xN/1632744420/2h40m/endpoints/Admin::UsersController%23index?responseTyp). Il faut [créer des colonnes tsvector](https://github.com/Casecommons/pg_search#using-tsvector-columns) https://github.com/betagouv/rdv-solidarites.fr/pull/1767 https://github.com/betagouv/rdv-solidarites.fr/pull/1768
* [x] [rdvs_overlapping.rb](https://www.skylight.io/app/applications/RgR7i58P67xN/1632744420/2h40m/endpoints/Admin::RdvWizardStepsController%23create?responseType=html). Utiliser `ends_at_in_range` semble assez lent; pour l’instant c’est fait avec `starts_at` et `duration_in_min`, on peut peut-être dénormaliser ou utiliser une colonne précalculée par PG. Ou alors, on peut simplement stocker `ends_at` en base. (#1787)
* [x] Liste des usagers dans le formulaire de recherche des rendez-vous: [rdvs/index.html.slim](https://www.skylight.io/app/applications/RgR7i58P67xN/1632744420/2h40m/endpoints/Admin::RdvsController%23index?responseType=html). On affiche la liste entière des usagers, et on compose le titre à la main (avec reverse_full_name) #1761 
* [x] Affichage des doublons dans [common/_user_attribute.html.slim](https://www.skylight.io/app/applications/RgR7i58P67xN/1632744420/2h40m/endpoints/Admin::UsersController%23show?responseType=html) A priori, c’est DuplicateUsersFinderService qui coûte cher, qui fait une requête sur le phone_number_formatted qui n’est pas indexé. (#1759)
* [x] Menu des agents dans [_left_menu.html.slim](https://www.skylight.io/app/applications/RgR7i58P67xN/1632744420/2h40m/endpoints/Admin::UsersController%23index?responseType=html). On affiche la liste de tous les agents, c’est cher en sql et en ruby. #1778
* [x] Affichage des badges sur les deux items statistiques dans [_left_menu.html.slim](https://www.skylight.io/app/applications/RgR7i58P67xN/1632744420/2h40m/endpoints/Admin::UsersController%23index?responseType=html) (#1757)
* [x] Affichage du formulaire de fusion d’usager (`merge_users/new`). Le formulaire affiche (deux fois) la liste complète des usagers de l’organisation, il faut utiliser la recherche texte. (#1784)

**Comment by n-b** [comment]
Je ferme ici; il y a 1838 pour la recherche de créneaux, pour le reste on pourra faire au fil de l'eau et créer des tickets spécifiques le cas échéant.
